service: event-ingestion
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-express
  - serverless-webpack
  # - serverless-domain-manager

package:
  individually: true
  include:
    - src/**/*.js
    - src/**/*.map.js
  exclude:
    - src/**/*.test.js
    - src/**/*.spec.js
    - node_modules/aws-sdk/**
    - coverage/**
    
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  # profile: default
  stage: ${opt:stage, 'dev'}

  apiKeys:
    - ${self:service}-${self:provider.stage}-apikey

  environment:
    DEBUG: 'api*'

functions:
  api:
    handler: src/lambda.handler
    name: v1-${self:service}-${self:provider.stage}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          private: true

  default-stream-consumer:
    handler: src/consumers/default.compute
    events:
      - stream:
          arn: ${cf:${self:service}-resources-${self:provider.stage}.DefaultStreamArn}
          batchSize: 1
          maximumRecordAgeInSeconds: 120
          startingPosition: LATEST
          enabled: true