---
AWSTemplateFormatVersion: '2010-09-09'
Description: Event Ingestion AWS Resources

Parameters:
  Environment:
    Type: String
    Description: The environment you're deploying to.
  ServiceName:
    Type: String
    Default: event-ingestion
  ThisServiceIamStackName:
    Type: String
    Default: ${ServiceName}-iam

Mappings:
  AccountParameterMap:
    StreamRetentionPeriodHours:
      # Dev acct. Sub this for your acct.
      "678960238302": 36

    StreamShardCountDefault:
      # Dev acct. Sub this for your acct.
      "678960238302": 1

Resources:
  KinesisStreamDefault:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Sub "${ServiceName}-default"
      ShardCount: !FindInMap [AccountParameterMap, "StreamShardCountDefault", !Ref "AWS::AccountId"]
      RetentionPeriodHours: !FindInMap [AccountParameterMap, "StreamRetentionPeriodHours", !Ref "AWS::AccountId"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis

  MaxRetryLambdaQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub "${ServiceName}-max-retry"

  DDBWriteQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      QueueName: !Sub "${ServiceName}-ddb-write.fifo"

  EventTable:
    Type: AWS::DynamoDB::Table

    # Keeps your table if you accidentally delete your cloudformation
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "${ServiceName}-events"

      # For backups
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      
      # Pay per request or'on demand' billing model
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id" # Needed for your hash key
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"

Outputs:
  DefaultStreamArn:
    Value: !GetAtt KinesisStreamDefault.Arn

  MaxRetryLambdaQueueArn:
    Value: !GetAtt MaxRetryLambdaQueue.Arn

  DDBWriteQueueArn:
    Value: !GetAtt DDBWriteQueue.Arn