Resources:
  AWSTemplateFormatVersion: '2010-09-09'
  Description: Event Ingestion AWS Resources

  Parameters:
    ServiceName:
      Type: String
      Default: event-ingestion
    ThisServiceIamStackName:
      Type: String
      Default: event-ingestion-iam

  ThisServiceIamStackInfo:
    Type: Custom::StackInfo
    Properties:
      ServiceToken: !ImportValue LookupStackOutputsArn
      StackName: !Ref ThisServiceIamStackName
      StackRegion: us-east-1

  KinesisStreamDefault:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Sub "${ServiceName}"
      # Re-enable when using multi-acct setup
      # ShardCount: !FindInMap [AccountParameterMap, "StreamShardCountDefault", !Ref "AWS::AccountId"]
      # RetentionPeriodHours: !FindInMap [AccountParameterMap, "StreamRetentionPeriodHours", !Ref "AWS::AccountId"]
      ShardCount: 1 # use moar shareds for moar scale :)
      RetentionPeriodHours: 24
      StreamEncryption:
          EncryptionType: KMS
          KeyId: alias/aws/kinesis
