name: sls deployment

on:
  push:
    branches: [master] # the branch we want this to run on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1

      - name: npm install
        run: npm i
      
      - name: deploy infrastructure
        run: |
          chmod +x ./scripts/deploy_infra.sh
          ./scripts/deploy_infra.sh dev